// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvR2ROAeeucYrqU3e18J7GE2qPRnasujk',
    appId: '1:665422451219:web:a0c9bde232650029c3e5e6',
    messagingSenderId: '665422451219',
    projectId: 'tapea-do',
    authDomain: 'tapea-do.firebaseapp.com',
    storageBucket: 'tapea-do.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoSRiuBwneDYDE0OGa3KzLT_Y2RzIq8w',
    appId: '1:665422451219:android:197e9f064b4fcbc5c3e5e6',
    messagingSenderId: '665422451219',
    projectId: 'tapea-do',
    storageBucket: 'tapea-do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK7zUEhQ7qYCXmKcu9O4DlNJOs4JWTE8s',
    appId: '1:665422451219:ios:6a492fcbf29fd7b3c3e5e6',
    messagingSenderId: '665422451219',
    projectId: 'tapea-do',
    storageBucket: 'tapea-do.appspot.com',
    iosClientId:
        '665422451219-gckv16ba3vlq49clorc50i2196tao8b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK7zUEhQ7qYCXmKcu9O4DlNJOs4JWTE8s',
    appId: '1:665422451219:ios:6a492fcbf29fd7b3c3e5e6',
    messagingSenderId: '665422451219',
    projectId: 'tapea-do',
    storageBucket: 'tapea-do.appspot.com',
    iosClientId:
        '665422451219-gckv16ba3vlq49clorc50i2196tao8b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapea',
  );
}
